services:
  - type: web
    name: fivemin-api
    runtime: docker
    rootDir: back
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    healthCheckPath: /api/symptoms
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMERGENCY_API_KEY
        sync: false
      - key: KAKAO_REST_KEY
        sync: false
      - key: KAKAO_REST_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
