export const HOSPITALS = [
  {
    id: 1,
    name: '서울아산병원',
    dist: '0.8km',
    wait: 85,
    beds: 3,
    tel: '02-3010-3114',
    lat: 37.527,
    lng: 127.1082,
    level: 'red',
    er24: true,
    peds: true,
    pedBeds: 8,
    warning: 'CT 장비 일시 점검 중 (오후 2~4시)',
    fav: true,
  },
  {
    id: 2,
    name: '삼성서울병원',
    dist: '2.1km',
    wait: 42,
    beds: 7,
    tel: '02-3410-2114',
    lat: 37.4881,
    lng: 127.0851,
    level: 'yellow',
    er24: true,
    peds: true,
    pedBeds: 5,
    warning: null,
    fav: false,
  },
  {
    id: 3,
    name: '서울대학교병원',
    dist: '3.4km',
    wait: 28,
    beds: 12,
    tel: '02-2072-2114',
    lat: 37.5796,
    lng: 126.9989,
    level: 'green',
    er24: true,
    peds: true,
    pedBeds: 10,
    warning: null,
    fav: true,
  },
  {
    id: 4,
    name: '강남세브란스병원',
    dist: '4.2km',
    wait: 55,
    beds: 4,
    tel: '02-2019-3114',
    lat: 37.4886,
    lng: 127.0656,
    level: 'red',
    er24: false,
    peds: false,
    pedBeds: 0,
    warning: '야간 소아과 의사 부재',
    fav: false,
  },
  {
    id: 5,
    name: '한림대강남성심병원',
    dist: '5.1km',
    wait: 18,
    beds: 15,
    tel: '02-829-5114',
    lat: 37.5107,
    lng: 126.9226,
    level: 'green',
    er24: true,
    peds: true,
    pedBeds: 3,
    warning: null,
    fav: false,
    moonBadge: true,
  },
];

export const LEVEL_COLOR = {
  green: '#1D9E75',
  yellow: '#BA7517',
  red:    '#E24B4A',
};

export const LEVEL_BG = {
  green: '#EAF3DE',
  yellow: '#FAEEDA',
  red:   '#FCEBEB',
};

export const LEVEL_LABEL = {
  green: '여유',
  yellow: '보통',
  red:   '혼잡',
};

export const SYMPTOMS = [
  { id: 'chest',      icon: '🫀', label: '가슴통증' },
  { id: 'stroke',     icon: '🧠', label: '뇌졸중 의심' },
  { id: 'breath',     icon: '🫁', label: '호흡 곤란' },
  { id: 'bleed',      icon: '🩸', label: '심한 출혈' },
  { id: 'burn',       icon: '🔥', label: '화상' },
  { id: 'bone',       icon: '🦴', label: '골절 의심' },
  { id: 'allergy',    icon: '⚠️', label: '알레르기 쇼크' },
  { id: 'unconscious',icon: '😵', label: '의식 저하' },
];